services:
  - type: web
    name: opal-tools
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /discovery
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_UID
        sync: false
      - key: API_KEY
        sync: false
